### PR TITLE
fixes for 7313 and 7512, plus some cleanup

### LINKED ISSUE #7313: Investigate: After withdrawal sdk state for useWallet and useRelay are not reverted
in `withDrawAllFunds` and `withdrawAllFundsEstimateGasCost` we calls `setUseWallet(false)` and `setUseRelay(false)` but never revert them back to their previous state.

This will likely cause a bug after someone withdraws.

Found by @robert-e-davidson3

### LINKED ISSUE #7512: When browser mesh not running, client attempts to use rpc even if its not configured
This happened on iOS.

image

### PR DESCRIPTION
**Pull request by robert-e-davidson3**

### CODE REVIEW

File: packages/augur-sdk/src/api/ZeroX.ts [hunk 1]
```diff
@@ -521,14 +521,18 @@ export class ZeroX {
     try {
       if (this._mesh) {
         return this._mesh.addOrdersAsync(orders);
-      } else {
+      } else if (this._rpc) {
         return this._rpc.addOrdersAsync(orders);
+      } else {
+        throw Error('0x rpc and browser mesh are undefined so orders cannot be created')
```
Comment (robert-e-davidson3) [inline packages/augur-sdk/src/api/ZeroX.ts]: This error message ends up being shown to the user so suggestions for better copy are appreciated.

File: packages/augur-sdk/src/state/create-api.ts [hunk 2]
```diff
@@ -125,11 +125,11 @@ export async function createClient(
     connector,
     zeroX,
     enableFlexSearch
-  );{}
+  );
 
   // Delay loading of the browser mesh until we're finished syncing
   client.events.once(SubscriptionEventName.BulkSyncComplete, () => {
-    if (config.zeroX?.mesh?.enabled && createBrowserMesh) {
+    if (!config?.sdk?.enabled && config.zeroX?.mesh?.enabled && createBrowserMesh) {
```
Comment (robert-e-davidson3) [inline packages/augur-sdk/src/state/create-api.ts:132]: We don't want to run the browser mesh if we're using the sdk server. This doesn't actually trigger as things stand because the BulkSyncComplete event doesn't get emitted when using the sdk server... but if that changes then this will prevent an error.

File: packages/augur-sdk/src/api/GSN.ts [hunk 3]
```diff
@@ -64,13 +64,20 @@ export class GSN {
       const signerAddress = await this.augur.dependencies.signer.getAddress();
       const walletAddress = await this.calculateWalletAddress(signerAddress);
       const wallet = this.augur.contracts.augurWalletFromAddress(walletAddress);
+
+      const useWallet = this.augur.getUseWallet();
```
Comment (robert-e-davidson3) [inline packages/augur-sdk/src/api/GSN.ts:68]: I didn't test this change as I'm not actually sure how to withdraw funds. @bthaile does this seem safe?

File: packages/augur-sdk/src/api/ZeroX.ts (hunk 1 above)
Comment (justinbarry) [reply packages/augur-sdk/src/api/ZeroX.ts]: Can we add something about *why* they are undefined?

**Review by nuevoalex — APPROVED** [review]
👍

File: packages/augur-sdk/src/api/ZeroX.ts (hunk 1 above)
Comment (pgebheim) [inline packages/augur-sdk/src/api/ZeroX.ts]:
```suggestion
        throw Error('Unable to fetch orders from ZeroX - The mesh has not yet been initialized or there is an error, and no RPC server was specified.')
```

**Review by pgebheim — CHANGES_REQUESTED** [review]

**Review by pgebheim — APPROVED** [review]
