### PR TITLE
Time polish for market creation

### LINKED ISSUE #3014: Timezone and endtime polish
Timezone and endtime stuff
- make hour and minutes and timezones coordinate
- Bug when going back
- make sure time displays corrrectly

### LINKED ISSUE #3030: Favorites button doesn't work on Market lIst page
Trying to click the star on the Markets List pg doesnt work - cant add to watchlist from there. Currently works doing it from the specific market trading pg

### PR DESCRIPTION
**Pull request by phoebemirman**
closes https://github.com/AugurProject/augur/issues/3014
closes https://github.com/AugurProject/augur/issues/3030

### CODE REVIEW

File: packages/augur-ui/src/modules/markets/reducers/new-market.ts [hunk 1]
```diff
@@ -50,10 +50,13 @@ export const DEFAULT_STATE: NewMarket = {
   designatedReporterType: DESIGNATED_REPORTER_SELF,
   designatedReporterAddress: "",
   endTime: null,
+  endTimeDropdown: null,
   tickSize: 0.01,
   hour: null,
   minute: null,
   meridiem: null,
+  offset: null,
```
Comment (bthaile) [inline packages/augur-ui/src/modules/markets/reducers/new-market.ts]: might as well default this to 0

**Review by bthaile — APPROVED** [review]
lgtm

**Comment by bthaile** [comment]
are the tix reference above "fixed" if so then type `fixed` or `closes` in front of tix url.
