### PR TITLE
Fix response values in getUserTradingPositions

### LINKED ISSUE #2612: changes to getUserTradingPositions getter
user's position needs to be in display terms

example:
      "position": "10000000000000000", needs to be       "position": ".1",

calculation issue with realized percent.
      "realizedPercent": "NaN",

timestamp is 0
      "timestamp": 0,a

### PR DESCRIPTION
**Pull request by adrake33**
Fixes https://github.com/AugurProject/augur/issues/2612

### CODE REVIEW

File: packages/augur-sdk/src/state/getter/Users.ts [hunk 1]
```diff
@@ -229,7 +229,9 @@ export class Users {
                 ].balance
               );
             }
-            tradingPosition.position = rawPosition.toFixed();
+            tradingPosition.position = rawPosition
```
Comment (bthaile) [inline packages/augur-sdk/src/state/getter/Users.ts]: I think I made a mistake on `position` the UI should use netPosition. `position` can be removed.

**Review by bthaile — APPROVED** [review]
lgtm, since we use netPosition, `position` property can be removed.
