### PR TITLE
fix spread

### LINKED ISSUE #3335: MC: order book doesn't update correctly
spread should be `-` like in the regular market trading page order book 

market trading page with only one bid

### LINKED ISSUE #3338: Spread display of order book in pre-liquidity state of market creation is incorrect
1) When only adding 1 side to the book - spread value should be a dash

2) This part is a bug:  Add Bid to the book, then add offer to the book.  Then add a better bid than before...the spread does not update, still displays original spread

### PR DESCRIPTION
**Pull request by phoebemirman**
closes https://github.com/AugurProject/augur/issues/3338
closes https://github.com/AugurProject/augur/issues/3335

### CODE REVIEW

File: packages/augur-ui/src/modules/create-market/helpers/format-order-book.ts [hunk 1]
```diff
@@ -8,26 +8,23 @@ import { LiquidityOrder, UIOrder, OutcomeOrderBook } from 'modules/types';
...
+export function formatOrderBook(outcomesOrderBook: LiquidityOrder[]): OutcomeOrderBook {
 	const bids = (outcomesOrderBook || []).filter((order: UIOrder) => order.type === BUY);
   const asks = (outcomesOrderBook || []).filter((order: UIOrder) => order.type === SELL);
   const orderBook: OutcomeOrderBook = {}
-  orderBook[ASKS] = asks;
-  orderBook[BIDS] = bids;
-  orderBook.spread = minPrice && maxPrice && calcSpread(asks, bids, minPrice, maxPrice);
+  orderBook[ASKS] = asks.sort((a, b) => createBigNumber(a.price).minus(createBigNumber(b.price)));
+  orderBook[BIDS] = bids.sort((a, b) => createBigNumber(b.price).minus(createBigNumber(a.price)));
+  console.log(orderBook[ASKS]);
```
Comment (bthaile) [inline packages/augur-ui/src/modules/create-market/helpers/format-order-book.ts]: remove console.logs

**Review by bthaile — APPROVED** [review]
lgtm

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://featurepeek.com). 💚

 This link will always point to this PR's latest changes: https://peek.run/0elhvww
