### PR TITLE
fixing random notification state issues. renaming variables for dispu…

### LINKED ISSUE #3856: UI issue: Disputing: disputing seems to never ends. Bonds just keep getting larger
UI issue: converting attoRep to attoRep makes for a really big number

disputing never ends event when timestamp is after Market's dispute window endTime.

I think the values are off by a factor. eventually market went to Awaiting Next Dispute Window, but the dispute bonds are in the millions.

reportingState: `CrowdsourcingDispute`
```json
{
  "bondSizeOfNewStake": "29304302839965820312502076",
  "disputePacingOn": true,
  "disputeWindow": {
    "disputeRound": "11",
    "endTime": 1571274000,
    "startTime": 1570669200
  },
  "stakeCompletedTotal": "14652151419982910156251038",
  "stakes": [
    {
      "bondSizeCurrent": "14654970966796875000001824",
      "isInvalidOutcome": false,
      "isMalformedOutcome": false,
      "outcome": "5",
      "stakeCurrent": "0",
      "stakeRemaining": "14654970966796875000001824",
      "tentativeWinning": false
    },
    {
      "bondSizeCurrent": "0",
      "isInvalidOutcome": false,
      "isMalformedOutcome": false,
      "outcome": "4",
      "stakeCurrent": "0",
      "stakeRemaining": "0",
      "tentativeWinning": true
    },
    {
      "bondSizeCurrent": "29301628156738281250001328",
      "isInvalidOutcome": false,
      "isMalformedOutcome": false,
      "outcome": "3",
      "stakeCurrent": "0",
      "stakeRemaining": "29301628156738281250001328",
      "tentativeWinning": false
    },
    {
      "bondSizeCurrent": "29304175074462890625002040",
      "isInvalidOutcome": false,
      "isMalformedOutcome": false,
      "outcome": "2",
      "stakeCurrent": "0",
      "stakeRemaining": "29304175074462890625002040",
      "tentativeWinning": false
    },
    {
      "bondSizeCurrent": "29304285741882324218752074",
      "isInvalidOutcome": false,
      "isMalformedOutcome": false,
      "outcome": "1",
      "stakeCurrent": "0",
      "stakeRemaining": "29304285741882324218752074",
      "tentativeWinning": false
    },
    {
      "bondSizeCurrent": "29304302839965820312502076",
      "isInvalidOutcome": true,
      "isMalformedOutcome": false,
      "outcome": "0",
      "stakeCurrent": "0",
      "stakeRemaining": "29304302839965820312502076",
      "tentativeWinning": false
    }
  ]
}
```

### LINKED ISSUE #3881: Disputing Form: progress bar displays black text
when adding too much REP progress bar has text

image

image

### PR DESCRIPTION
**Pull request by bthaile**
…ting to be more clear.

fixes https://github.com/AugurProject/augur/issues/3881
fixes https://github.com/augurproject/augur/issues/3856

random notification fixes. 
rename variables to be come clear

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://featurepeek.com). 😁

 This link will always point to this PR's latest changes: https://peek.run/g7oh4pz

File: packages/augur-ui/src/modules/modal/reporting.tsx [hunk 1]
```diff
@@ -84,7 +84,7 @@ export default class ModalReporting extends Component<
         numOutcomes,
         marketType,
         description: '',
-        amount: this.state.preFilledStake,
+        attoRepAmount: this.state.preFilledStake,
```
Comment (bconfortin) [inline packages/augur-ui/src/modules/modal/reporting.tsx:87]: From a newcomer's standpoint, this is much better to understand. Thank you for that :smile:

**Review by bconfortin — APPROVED** [review]
