### PR TITLE
liquidity / market depth fix

### LINKED ISSUE #3027: Create Market - Initial Liquidity
Fix market depth chart to not be flat.

### PR DESCRIPTION
**Pull request by andrewdamelio**
fixes #3027 

- misc fixes
- The depth chart will show tooltips now
- The depth chart will not be flat
- Depth chart / Order book now shows correct cumulative shares

### CODE REVIEW

File: packages/augur-ui/src/modules/markets/reducers/new-market.ts [hunk 1]
```diff
@@ -78,22 +78,25 @@ export default function(newMarket: NewMarket = DEFAULT_STATE, { type, data }: Ba
...
-        const orderInfo = Object.assign({}, order);
+
+      const updatedOrders = existingOrders.map((order: LiquidityOrder) => {
+          const orderInfo = Object.assign({}, order);
         if (createBigNumber(order.price).eq(createBigNumber(price)) && order.type === type) {
-          orderInfo.quantity = createBigNumber(order.quantity).plus(createBigNumber(quantity)).toNumber();
+          orderInfo.quantity = createBigNumber(order.quantity).plus(createBigNumber(quantity)).toString();
+          orderInfo.shares = createBigNumber(order.quantity).plus(createBigNumber(quantity)).toString();
           orderInfo.orderEstimate = createBigNumber(order.orderEstimate).plus(
             createBigNumber(orderEstimate.replace(" DAI", ""))
```
Comment (bthaile) [inline packages/augur-ui/src/modules/markets/reducers/new-market.ts:93]: not a fan of this logic, shouldn't be removing a string in order to treat something like a number.  need to just add `totalCost` to order that is used in new Market reducer and not parse out order estimate.

**Review by bthaile — APPROVED** [review]
lgtm, some legacy crap code, but can be addressed at future time.
