### PR TITLE
Cleanup and Server WS fix

### LINKED ISSUE #2301: Events can't emit from state's server
For some reason events won't emit from state's server.

Make them emit and go back through the websocket.

### PR DESCRIPTION
**Pull request by brianosaurus**
Closes #2301 

* Adds messages for websocket state changes
* Cleanup of imports on connectors
* Fixes websocket closing bug in the state server
* Fixes querying of data in state's server

### CODE REVIEW

File: packages/augur-sdk/src/state/index.ts [hunk 1]
```diff
@@ -23,13 +23,23 @@ console.log("Starting web worker");
...
+      console.log(data);
+      augur.off(SubscriptionEventNames.Burn);
+    });
+
+    augur.on(SubscriptionEventNames.Approval, (data: any): void => {
+      console.log(data);
+      augur.off(SubscriptionEventNames.Approval);
+    });
+
     setTimeout(async () => {
```
Comment (bthaile) [inline packages/augur-sdk/src/state/index.ts]: Why does this setTimeout(...) exist

Comment (brianosaurus) [reply packages/augur-sdk/src/state/index.ts]: Removed it. It was there because of the web worker. The worker needs time to ingest data.

**Review by bthaile — APPROVED** [review]
lgtm
