### PR TITLE
fix auto selection of CB wallet

### LINKED ISSUE #10167: Don't highlight connect to coinbase wallet when not connected (the green outline and dot indicates the user is currently connected with this wallet)
image

### PR DESCRIPTION
**Pull request by andrewdamelio**
fixes #10167

### CODE REVIEW

File: packages/augur-simplified/src/modules/modal/modal-connect-wallet.tsx [hunk 1]
```diff
@@ -132,6 +132,7 @@ const ModalConnectWallet = ({
   transactions,
 }: ModalConnectWalletProps) => {
   const {
+    loginAccount,
```
Comment (JohnDanz) [inline packages/augur-simplified/src/modules/modal/modal-connect-wallet.tsx]: use isLogged

**Review by JohnDanz — APPROVED** [review]
