### PR TITLE
typescript fixes

### LINKED ISSUE #2259: Fix TypeScript errors

### PR DESCRIPTION
**Pull request by andrewdamelio**
#2259 -  starts fixing the errors generated by ```--type-checking``` so we can eventually turn on --type-checking as part of our workflow.

## First pass at the below folders
- [x] /account/actions
- [x] /account/containers
- [x] /account/components

### CODE REVIEW

File: packages/augur-ui/src/modules/account/components/profit-loss-chart.tsx [hunk 1]
```diff
@@ -87,76 +90,78 @@ export default class ProfitLossChart extends Component<
...
+        0,
+      ),
     );
 
     const max = formatEther(bnMax, { decimalsRounded: 4 }).formattedValue;
     const min = formatEther(bnMin, { decimalsRounded: 4 }).formattedValue;
     const tickInterval = bnMax.abs().gt(bnMin.abs())
-      ? formatEther(bnMax.abs()).formattedValue
-      : formatEther(bnMin.abs()).formattedValue;
+      ? formatEther(bnMax.abs(), {}).formattedValue
```
Comment (bthaile) [inline packages/augur-ui/src/modules/account/components/profit-loss-chart.tsx]: don't need `{}` on formatEther or any of the format number calls

File: packages/augur-ui/src/modules/account/components/stats.tsx [hunk 2]
```diff
@@ -3,7 +3,7 @@ import React from "react";
 import { LinearPropertyLabel } from "modules/common-elements/labels";
 import { formatNumber } from "utils/format-number";
 
-import Styles from "modules/account/components/stats.styles";
+import Styles from "modules/account/components/stats.styles.less";
```
Comment (bthaile) [inline packages/augur-ui/src/modules/account/components/stats.tsx:6]: is there a plan to remove `.less` in the future? I'm ok with adding them temporary but I'd like to know how we are going to get rid of them.

File: packages/augur-ui/src/modules/account/components/profit-loss-chart.tsx (hunk 1 above)
Comment (bthaile) [reply packages/augur-ui/src/modules/account/components/profit-loss-chart.tsx]: I fixed and committed.

**Review by bthaile — APPROVED** [review]
a comment we can chat about addressing `.less` in later PR
