### PR TITLE
make it so pending liquidity shows up for retry

### LINKED ISSUE #3284: make pending orders stick around if market creation fails and you retry

### PR DESCRIPTION
**Pull request by phoebemirman**
closes https://github.com/AugurProject/augur/issues/3284

### CODE REVIEW

File: packages/augur-ui/src/modules/create-market/helpers/construct-market-params.ts [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+  tickSizeToNumTickWithDisplayPrices,
+} from '@augurproject/sdk';
+import { BigNumber } from 'bignumber.js';
+import {
+  SCALAR,
+  CATEGORICAL,
+  TEN_TO_THE_EIGHTEENTH_POWER,
+} from 'modules/common/constants';
+
+export function generateTxParameters(newMarket: NewMarket, copyReturn: Boolean): TransactionMetadataParams {
```
Comment (bthaile) [inline packages/augur-ui/src/modules/create-market/helpers/construct-market-params.ts]: not sure what `copyReturn` means here

File: packages/augur-ui/src/modules/markets/actions/submit-new-market.ts [hunk 2]
```diff
@@ -12,49 +12,77 @@ import { createBigNumber } from "utils/create-big-number";
...
+import { NodeStyleCallback, NewMarket, CreateMarketData } from "modules/types";
 import { ThunkDispatch } from "redux-thunk";
 import { Action } from "redux";
 import { createMarket } from "modules/contracts/actions/contractCalls";
 import { checkAccountAllowance } from "modules/auth/actions/approve-account";
+import { generateTxParameterId } from 'utils/generate-tx-parameter-id';
+import { generateTxParameters } from 'modules/create-market/helpers/construct-market-params';
+import { createMarketRetry } from "modules/contracts/actions/contractCalls";
 
 export function submitNewMarket(
```
Comment (bthaile) [inline packages/augur-ui/src/modules/markets/actions/submit-new-market.ts:26]: I'm not a fan of callers having to know what parameters need to be null. Create pass through methods to make it more clear what is being done in the calling code.

File: packages/augur-ui/src/modules/modal/containers/modal-create-market.ts [hunk 3]
```diff
@@ -18,7 +18,7 @@ const mapStateToProps = (state: AppState) => ({
 const mapDispatchToProps = (dispatch: ThunkDispatch<void, any, Action>) => ({
   closeModal: () => dispatch(closeModal()),
   submitNewMarket: (data: NewMarket, cb: NodeStyleCallback) =>
-    dispatch(submitNewMarket(data, cb)),
+    dispatch(submitNewMarket(data, null, false, cb)),
```
Comment (bthaile) [inline packages/augur-ui/src/modules/modal/containers/modal-create-market.ts]: example of a the place to have more descriptive method instead of passing in null, false
just create a new pass through method `createNewMarket` as an example

File: packages/augur-ui/src/modules/portfolio/containers/my-markets.ts [hunk 4]
```diff
@@ -23,7 +25,7 @@ const mapStateToProps = (state) => {
 // TOJDO confirm with TOm whats up with this, getBalance Only
 const mapDispatchToProps = (dispatch) => ({
   removePendingMarket: (id) => dispatch(removePendingData(id, CREATE_MARKET)),
-  createMarketRetry: (data) => dispatch(createMarketRetry(data)),
+  createMarketRetry: (data) => dispatch(submitNewMarket(null, data, true)),
```
Comment (bthaile) [inline packages/augur-ui/src/modules/portfolio/containers/my-markets.ts]: here is a place to have a more descriptive method call, maybe call it `retryCreateMarket` and only pass in `data`

**Comment by bthaile** [comment]
Let me know how testing goes. 
YesNo market creation
 - [x] with orders,  
 - [x] without orders

Scalar market creation
 - [x] with orders, 
 - [x] without orders

Categorical market creation
 - [x] with orders, 
 - [x] without orders

File: packages/augur-ui/src/modules/markets/actions/submit-new-market.ts [hunk 5]
```diff
@@ -12,55 +12,106 @@ import { createBigNumber } from "utils/create-big-number";
...
+    if (hasOrders) {
+      dispatch(
+        addMarketLiquidityOrders({
+          marketId: pendingId,
+          liquidityOrders: sortOrderBook
+        })
+      );
+    }
+
+    const marketResult = await createMarketRetry(market);
```
Comment (bthaile) [inline packages/augur-ui/src/modules/markets/actions/submit-new-market.ts:101]: what happens if user closes browser after signing create market tx?

Comment (bthaile) [reply packages/augur-ui/src/modules/markets/actions/submit-new-market.ts:101]: we'll need to cover this edge case in another PR

**Review by bthaile — APPROVED** [review]
lgtm

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://featurepeek.com). 🍻

 This link will always point to this PR's latest changes: https://peek.run/1rehx0l
