### PR TITLE
1946 fix log processing in v2 augur node

### LINKED ISSUE #1946: Fix augur-node v2 decrease token balance and create markets log processors
Issues remaining to get vs augur-node processing contract logs

* decrease token balance fails
* the create-market log processor fails when run outside of the debugger
* market creation fees should be removed from
  1. markets sql table
  1.  log processor

### PR DESCRIPTION
**Pull request by brianosaurus**
Closes #1946 

* Logs are processed in the correct order
* Integrates changes to the structure of market created logs

### CODE REVIEW

**Review by adrake33 — APPROVED** [review]
LGTM

File: packages/augur-node/src/blockchain/download-augur-logs.ts [hunk 1]
```diff
@@ -12,7 +12,7 @@ import { ParsedLog } from "@augurproject/api";
 const BLOCK_DOWNLOAD_PARALLEL_LIMIT = 15;
 
 interface BlockDetailsByBlock {
-  [blockNumber: number]: BlockDetail;
+  [blockNumbe: number]: BlockDetail;
```
Comment (pgebheim) [inline packages/augur-node/src/blockchain/download-augur-logs.ts]:
```
blockNumber
```

**Review by pgebheim — CHANGES_REQUESTED** [review]
Looks like one typo

**Review by pgebheim — APPROVED** [review]
