### PR TITLE
Pg/add mesh events

### LINKED ISSUE #7404: Add events for mesh browser crash and peers count
1. If mesh browser client crashes emit event out event that UI can use. 
2. When mesh browser client connects / disconnects to peers emit event with number of connected peers.

### PR DESCRIPTION
**Pull request by pgebheim**
Closes #7404

### CODE REVIEW

File: packages/augur-ui/src/services/browser-mesh.ts [hunk 1]
```diff
@@ -118,5 +120,6 @@ export async function createBrowserMesh(
   const mesh = new Mesh(meshConfig);
   mesh.onError(createBrowserMeshRestartFunction(meshConfig, web3Provider, zeroX, config));
   await mesh.startAsync();
+  zeroX.client.emit('ZeroX:State:Started');
```
Comment (bthaile) [inline packages/augur-ui/src/services/browser-mesh.ts]: can you use a constant, so that there isn't a typo somewhere. 

`packages/augur-sdk/src/constants.ts`
SubscriptionEventName

File: packages/augur-ui/src/services/browser-mesh.ts [hunk 2]
```diff
@@ -63,25 +63,27 @@ function createBrowserMeshRestartFunction(
...
+        sdkConfig.addresses,
+        meshConfig.verbosity,
+        meshConfig.useBootstrapList,
+        meshConfig.bootstrapList,
+        true
+      )
+    );
+    mesh.onError(createBrowserMeshRestartFunction(meshConfig, web3Provider, zeroX, sdkConfig));
+    mesh.startAsync().then(() => {
+      zeroX.client.emit('ZeroX:State:Restarted');
```
Comment (bthaile) [inline packages/augur-ui/src/services/browser-mesh.ts]: SubscriptionEventName,
constant please

File: packages/augur-ui/src/services/browser-mesh.ts [hunk 3]
```diff
@@ -63,25 +63,27 @@ function createBrowserMeshRestartFunction(
 ) {
   return err => {
     console.error('Browser mesh error: ', err.message, err.stack);
-      console.log('Restarting Mesh Sync');
+    console.log('Restarting Mesh Sync');
+    zeroX.client.emit('ZeroX:State:Restarting', {error: err});
```
Comment (bthaile) [inline packages/augur-ui/src/services/browser-mesh.ts]: SubscriptionEventName
constant please, just to drive the point home. 😆

**Review by bthaile — APPROVED** [review]
lgtm

File: packages/augur-sdk/src/api/ZeroX.ts [hunk 4]
```diff
@@ -158,7 +164,7 @@ export class ZeroX {
       throw Error(`Failure when subscribing to OrdersAsync in ZeroX set rpc: ${err}`);
```
Comment (bthaile) [inline packages/augur-sdk/src/api/ZeroX.ts:164]: should this emit an event saying the client is dead?
